name: AutoRegionGuard
main: net.peoplero.arg.ARG
version: 0.5
description: AutoRegionGuard Protects areas that you build in automatically.
author: Friesnadrink
website: arg.peoplero.net
commands:
  arg:
    description: arg toggle thing
    usage: |
           /<command> [toggle, info, addfriend, removefriend, friends, unclaim, claim, removeplayer, save, load]
           Example: /<command> toggle
  god:
    description: Godmode Command
    usage: |
           /<command> [playername]
           Example: /<command> Timmy